services:
  app:
    build: .
    container_name: app
    environment:
      - API_PORT=1323
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./api
        target: /app/api
      - type: bind
        source: ./client
        target: /app/client
